#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots
{
    MUGSHOT_NONE,
    MUGSHOT_PLAYER,
    MUGSHOT_COUNT,
};

enum MugshotEmotes
{
    EMOTE_NORMAL,
    EMOTE_ALT,
    EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
